---
openapi: 3.0.1
info:
  title: API v1
  version: v1
paths:
  "/api/v1/performances":
    get:
      summary: list performances
      responses:
        '200':
          description: successful
    post:
      summary: create performance
      tags:
      - Performances
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: file
        required: true
  "/api/v1/performances/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show performance
      responses:
        '200':
          description: successful
    put:
      summary: update performance
      responses:
        '200':
          description: successful
    delete:
      summary: delete performance
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
