default: &default
  adapter: postgresql
  encoding: utf8
  database: "<%= ENV['DATABASE_NAME'] %>"
  username: "<%= ENV['DATABASE_USER'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
  host: "<%= ENV['DATABASE_HOST'] %>"
  port: <%= ENV['DATABASE_PORT'] || 5432 %>

development:
  <<: *default

test:
  <<: *default
  database: portfolio_test

production: &production
  <<: *default
  pool: <%= ENV['DATABASE_POOL_SIZE'] || 5 %>
